<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'packages/src/Exception.php';
require 'packages/src/PHPMailer.php';
require 'packages/src/SMTP.php';

// PHPMailer Object
$mail = new PHPMailer();

$mail->isSMTP();
$mail->Host = 'http://mbox.myshoptet.com/';
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->SMTPAuth = true;
$mail->Username = 'info@armysvet.cz'; //paste one generated by Mailtrap
$mail->Password = 'bigheadawyb0r0'; //paste one generated by Mailtrap

// From email address and name
$mail->From = "test@test.cz"; // replace to your own domain
$mail->FromName = "Mirda"; // replace to your own name

// To address and name
$mail->addAddress("miroslav@slusarcik.cz");
//$mail->addAddress("recepient1@example.com"); // Recipient name is optional

// Address to which recipient will reply
$mail->addReplyTo("test@test.cz", "Reply");

// CC and BCC
//$mail->addCC("cc@example.com");
//$mail->addBCC("bcc@example.com");

// Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "Nová objednávka prohlídky";
$mail->Body = "<i>Mail body in HTML</i>";
$mail->AltBody = "This is the plain text version of the email content";

if(!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} 
else {
    echo "Message has been sent successfully.";
}
?>